const fs = require('fs');
const path = require('node:path');

jsonPath = path.join(__dirname,'tokens.json');

data = JSON.parse(`{
    "accessToken" : "eyJhbGciOiJIUzI1NiIsImVudiI6InRyYWNrbWFuaWEtcHJvZCIsInZlciI6IjEifQ.eyJqdGkiOiJlZjkwMDk2YS0zYzExLTExZWYtYTVjMy0wNjk1OTZjMjY3NWYiLCJpc3MiOiJOYWRlb1NlcnZpY2VzIiwiaWF0IjoxNzIwMzIzMzIwLCJyYXQiOjE3MjAzMjUxMjAsImV4cCI6MTcyMDMyNjkyMCwiYXVkIjoiTmFkZW9TZXJ2aWNlcyIsInVzZyI6IkNsaWVudCIsInNpZCI6ImVmOTAwNjVlLTNjMTEtMTFlZi1iOWQ4LTA2OTU5NmMyNjc1ZiIsInNhdCI6MTcyMDMyMzMyMCwic3ViIjoiMjA2ZGQwYjUtMWQxZS00Y2U3LWJlZjItMzg4ZDEzYzdiODUzIiwiYXVuIjoiZmxhcHB5cHJpbmNlIiwicnRrIjpmYWxzZSwicGNlIjpmYWxzZSwidWJpc2VydmljZXNfdWlkIjoiZTUzYmNlMzUtOWI1NS00MDMwLWEyMjctNjhmMGU1OTUzZjA3In0.e3cWOKtGLyd4qMPqcItI6abxFuRaz9eTdb_vcnlWDpw",
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsImVudiI6InRyYWNrbWFuaWEtcHJvZCIsInZlciI6IjEifQ.eyJqdGkiOiJlZjkwMTY0NC0zYzExLTExZWYtYmNhMS0wNjk1OTZjMjY3NWYiLCJpc3MiOiJOYWRlb1NlcnZpY2VzIiwiaWF0IjoxNzIwMzIzMzIwLCJyYXQiOjE3MjAzNjY1MjAsImV4cCI6MTcyMDQwOTcyMCwiYXVkIjoiTmFkZW9TZXJ2aWNlcyIsInVzZyI6IkNsaWVudCIsInNpZCI6ImVmOTAwNjVlLTNjMTEtMTFlZi1iOWQ4LTA2OTU5NmMyNjc1ZiIsInNhdCI6MTcyMDMyMzMyMCwic3ViIjoiMjA2ZGQwYjUtMWQxZS00Y2U3LWJlZjItMzg4ZDEzYzdiODUzIiwiYXVuIjoiZmxhcHB5cHJpbmNlIiwicnRrIjp0cnVlLCJwY2UiOmZhbHNlLCJ1YmlzZXJ2aWNlc191aWQiOiJlNTNiY2UzNS05YjU1LTQwMzAtYTIyNy02OGYwZTU5NTNmMDciLCJyZWZyZXNoX2F1ZCI6Ik5hZGVvU2VydmljZXMiLCJsaW1pdF90eXBlIjoibm9uZSJ9._MGIdmy6F_nYOV7kAvY6pDOJIHsI39h6oFWB0LMPazM",
    "accessExpiry" : ""
}`, 'utf-8')

data.accessExpiry = JSON.stringify(Date.now())

console.log(data)

